"""Asset registry: which symbols we trade, and how each one actually behaves.

Two facts drive this module.

**Public market data is not OTC data.** On PocketOption an "OTC" instrument is
synthetic price action generated by the platform, and it is a genuinely
different distribution from the real market. A strategy validated on Yahoo
EUR/USD candles has not been validated on PocketOption EUR/USD OTC. The `feed`
tier in :class:`Asset` records which world a symbol's candles come from so the
scorer can refuse to treat a public-FX read as if it were an OTC read.

**Payout is a property of the instrument, not the market.** OTC pairs on
PocketOption usually quote 85-92% while majors quote 80-87%, and it drifts with
volatility. Hardcoding 92% is how you end up approving a trade whose break-even
is actually 55%. :func:`payout_for` gives a conservative default per tier and
expects the caller to override with the live quote.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

# Which data world a symbol's candles describe.
FEED_PUBLIC = "public"   # real market feed (Yahoo, etc.)
FEED_OTC = "otc"         # platform synthetic OTC instrument
FEED_USER = "user"       # user's own exported/screenshot data
FEED_UNKNOWN = "unknown"


@dataclass
class Asset:
    symbol: str                 # PocketOption display name, e.g. "EUR/USD OTC"
    po_symbol: str              # platform label as shown in the UI
    base: str
    quote: str
    kind: str = "fx"            # fx | crypto | commodity | index
    otc: bool = True
    feed: str = FEED_OTC
    yahoo: Optional[str] = None  # public-feed symbol, when one exists
    default_payout: float = 92.0
    typical_range: Optional[Tuple] = None  # (lo, hi) typical 5m ATR in price units
    notes: str = ""

    @property
    def public_feed(self) -> bool:
        return self.feed == FEED_PUBLIC

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "po_symbol": self.po_symbol,
            "kind": self.kind,
            "otc": self.otc,
            "feed": self.feed,
            "yahoo": self.yahoo,
            "default_payout": self.default_payout,
            "notes": self.notes,
        }


Tuple = tuple  # noqa: E305  (kept local so the dataclass annotation above stays simple)


def _a(symbol, po, base, quote, yahoo, payout, kind="fx", otc=True, feed=FEED_OTC, notes=""):
    return Asset(symbol, po, base, quote, kind, otc, feed, yahoo, payout, None, notes)


# The OTC majors the blueprint trades, plus the public equivalents we can
# actually pull candles for. The pairing matters: it is the only way to do
# anything quantitative before the user exports real OTC history.
ASSETS: List[Asset] = [
    _a("EUR/USD OTC", "EUR/USD OTC", "EUR", "USD", "EURUSD=X", 92.0,
       notes="Primary blueprint instrument. Highest OTC payout tier."),
    _a("GBP/USD OTC", "GBP/USD OTC", "GBP", "USD", "GBPUSD=X", 92.0,
       notes="Higher realised vol than EUR, wider stops needed."),
    _a("USD/JPY OTC", "USD/JPY OTC", "USD", "JPY", "JPY=X", 90.0,
       notes="Quote in JPY; pip arithmetic and decimal handling differ."),
    _a("AUD/CAD OTC", "AUD/CAD OTC", "AUD", "CAD", "AUDCAD=X", 87.0,
       notes="Quieter session, thin OTC book."),
    _a("EUR/GBP OTC", "EUR/GBP OTC", "EUR", "GBP", "EURGBP=X", 87.0,
       notes="Very low vol; usually fails the volatility filter by design."),
    _a("USD/CHF OTC", "USD/CHF OTC", "USD", "CHF", "CHF=X", 89.0,
       notes="Rarely the strongest CHF play; treat cautiously."),
    _a("NZD/USD OTC", "NZD/USD OTC", "NZD", "USD", "NZDUSD=X", 88.0,
       notes="Reactive to risk sentiment, gaps on news."),

    # Public instruments: real market, no synthetic OTC counterpart.
    _a("EUR/USD (public)", "EUR/USD", "EUR", "USD", "EURUSD=X", 87.0,
       otc=False, feed=FEED_PUBLIC, notes="Real market. Backtest-only reference."),
    _a("BTC/USD (public)", "BTC/USD", "BTC", "USD", "BTC-USD", 80.0,
       kind="crypto", otc=False, feed=FEED_PUBLIC,
       notes="24/7; session filters are meaningless."),

    # Crypto OTC offered on PocketOption.
    _a("BTC/USD OTC", "BTC/USD OTC", "BTC", "USD", "BTC-USD", 85.0,
       kind="crypto", notes="No trading session; macro news dominates."),
    _a("ETH/USD OTC", "ETH/USD OTC", "ETH", "USD", "ETH-USD", 83.0,
       kind="crypto", notes="Correlation to BTC is the dominant feature."),
]

def _register(asset: Asset) -> None:
    """Index an asset under every name a trader might type for it.

    Ambiguity policy: this app exists to trade PocketOption OTC, so when a bare
    name like "EUR/USD" could mean either the OTC instrument or the public one,
    OTC wins. Callers reach the public variant only by asking for it explicitly
    ("EUR/USD (public)"). Silently swapping a synthetic OTC instrument for the
    real market -- or the reverse -- is exactly the kind of quiet substitution
    that makes a backtest meaningless.
    """
    bare = f"{asset.base}/{asset.quote}".lower()
    for k in (asset.symbol.lower(), asset.po_symbol.lower(), bare):
        _BY_NAME.setdefault(k, asset)


_BY_NAME: Dict[str, Asset] = {}
for _asset in sorted(ASSETS, key=lambda a: 0 if a.otc else 1):
    _register(_asset)


def _squash(s: str) -> str:
    return "".join(ch for ch in s.lower() if ch.isalnum())


def resolve(name: str) -> Optional[Asset]:
    """Best-effort lookup tolerating the spacing the platform actually uses."""
    if not name:
        return None
    k = name.strip().lower()
    if k in _BY_NAME:
        return _BY_NAME[k]
    target = _squash(k)
    if not target:
        return None
    # Punctuation-insensitive second pass. Ordered so OTC wins ties here too --
    # otherwise "eurusd" fuzzy-matches the public instrument, because the OTC
    # key squashes to "eurusdotc" and never competes.
    ordered = sorted(_BY_NAME.items(), key=lambda kv: (0 if kv[1].otc else 1,))
    for key, asset in ordered:
        if _squash(key) == target:
            return asset
    return None


def payout_for(name: str, fallback: float = 92.0) -> float:
    """Default payout as a PERCENT, e.g. 92.0.

    Always prefer the live value read off the platform. This is a floor-safe
    default, not a quote.
    """
    a = resolve(name)
    return a.default_payout if a else fallback


def list_assets(include_public: bool = True) -> List[dict]:
    return [a.to_dict() for a in ASSETS if include_public or a.feed != FEED_PUBLIC]


def session_filter_ok(
    name: str, hour_utc: int, killzone_only: bool = True
) -> bool:
    """London/NY overlap check.

    Expressed in UTC because the platform's own clock is not always the
    broker's. FX OTC dies outside the overlap, and a detector that fires on
    dead-session drift is noise the scorer should never rank.
    """
    a = resolve(name)
    if a is None or a.kind == "crypto":
        return True          # 24/7 market: no session concept
    if not killzone_only:
        return True
    # London 07:00-16:00 UTC, NY 12:00-21:00 UTC; keep the 12:00-16:00 overlap
    # plus a shoulder on either side.
    return 7 <= hour_utc <= 21


def news_blackout_windows(weekday_utc: int, hour_utc: int) -> List[str]:
    """Recurring high-impact release hours, UTC.

    Approximate on purpose. This is a filter to avoid the worst of it, not a
    calendar; the real check is the user's own news toggle in the platform.
    """
    out: List[str] = []
    if weekday_utc == 3 and 12 <= hour_utc <= 15:      # Wed US CPI / FOMC
        out.append("US CPI/FOMC window")
    if weekday_utc == 4 and 12 <= hour_utc <= 14:      # Thu ECB / claims
        out.append("US claims / ECB window")
    if hour_utc in (13, 14) and weekday_utc in (1, 2, 4, 5):
        out.append("US data release (13:30 UTC typical)")
    if weekday_utc == 0 and 13 <= hour_utc <= 16:
        out.append("Week open gap risk")
    return out
